// *********** THIS FILE IS GENERATED - DO NOT EDIT ***********
//     See cpp_generator.py for modifications
// ************************************************************

/*
** Copyright (c) 2017-2021 The Khronos Group Inc.
** Copyright (c) 2019-2021 Collabora, Ltd.
**
** Licensed under the Apache License, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
**
**     http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
**
** ---- Exceptions to the Apache 2.0 License: ----
**
** As an exception, if you use this Software to generate code and portions of
** this Software are embedded into the generated code as a result, you may
** redistribute such product without providing attribution as would otherwise
** be required by Sections 4(a), 4(b) and 4(d) of the License.
**
** In addition, if you combine or link code generated by this Software with
** software that is licensed under the GPLv2 or the LGPL v2.0 or 2.1
** ("`Combined Software`") and if a court of competent jurisdiction determines
** that the patent provision (Section 3), the indemnity provision (Section 9)
** or other Section of the License conflicts with the conditions of the
** applicable GPL or LGPL license, you may retroactively and prospectively
** choose to deem waived or otherwise exclude such Section(s) of the License,
** but only in their entirety and only with respect to the Combined Software.
**
*/

/*
** This header is generated from the Khronos OpenXR XML API Registry.
**
*/
#ifndef OPENXR_METHOD_IMPLS_HPP_
#define OPENXR_METHOD_IMPLS_HPP_
/**
 * @file
 * @brief Includes the appropriate subset of method implementations based on chosen configuration.
 *
 * @ingroup handles
 * @ingroup api_free_functions
 */

#include "openxr_handles.hpp"
#include "openxr_structs.hpp"

#include "openxr_method_impls_simple.inl"

#if !defined(OPENXR_HPP_DISABLE_ENHANCED_MODE)
#include "openxr_method_impls_enhanced.inl"

#if !defined(OPENXR_HPP_NO_EXCEPTIONS)
#include "openxr_method_impls_enhanced_exceptions.inl"
#endif  // !defined(OPENXR_HPP_NO_EXCEPTIONS)

#endif  // !defined(OPENXR_HPP_DISABLE_ENHANCED_MODE)

#endif  // ifndef OPENXR_METHOD_IMPLS_HPP_
