// *********** THIS FILE IS GENERATED - DO NOT EDIT ***********
//     See cpp_generator.py for modifications
// ************************************************************

/*
** Copyright (c) 2017-2021 The Khronos Group Inc.
** Copyright (c) 2019-2021 Collabora, Ltd.
**
** Licensed under the Apache License, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
**
**     http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
**
** ---- Exceptions to the Apache 2.0 License: ----
**
** As an exception, if you use this Software to generate code and portions of
** this Software are embedded into the generated code as a result, you may
** redistribute such product without providing attribution as would otherwise
** be required by Sections 4(a), 4(b) and 4(d) of the License.
**
** In addition, if you combine or link code generated by this Software with
** software that is licensed under the GPLv2 or the LGPL v2.0 or 2.1
** ("`Combined Software`") and if a court of competent jurisdiction determines
** that the patent provision (Section 3), the indemnity provision (Section 9)
** or other Section of the License conflicts with the conditions of the
** applicable GPL or LGPL license, you may retroactively and prospectively
** choose to deem waived or otherwise exclude such Section(s) of the License,
** but only in their entirety and only with respect to the Combined Software.
**
*/

/*
** This header is generated from the Khronos OpenXR XML API Registry.
**
*/
#ifndef OPENXR_DURATION_HPP_
#define OPENXR_DURATION_HPP_
/**
 * @file
 * @brief Contains a type-safe C++ projection of XrDuration
 *
 * @see openxr_time.hpp, xr::Duration
 * @ingroup wrappers
 */

#include <openxr/openxr.h>

#if !defined(OPENXR_HPP_INLINE)
#if defined(__clang___)
#if __has_attribute(always_inline)
#define OPENXR_HPP_INLINE __attribute__((always_inline)) __inline__
#else
#define OPENXR_HPP_INLINE inline
#endif
#elif defined(__GNUC__)
#define OPENXR_HPP_INLINE __attribute__((always_inline)) __inline__
#elif defined(_MSC_VER)
#define OPENXR_HPP_INLINE inline
#else
#define OPENXR_HPP_INLINE inline
#endif
#endif  // !OPENXR_HPP_INLINE

#if !defined(OPENXR_HPP_CONSTEXPR)
#if defined(_MSC_VER) && (_MSC_VER <= 1800)
#define OPENXR_HPP_CONSTEXPR
#else
#define OPENXR_HPP_CONSTEXPR constexpr
#endif
#endif  // !OPENXR_HPP_CONSTEXPR

#if !defined(OPENXR_HPP_SWITCH_CONSTEXPR)
//! @todo set this to constexpr in c++14
#define OPENXR_HPP_SWITCH_CONSTEXPR
#endif  // !OPENXR_HPP_SWITCH_CONSTEXPR

#if !defined(OPENXR_HPP_NAMESPACE)
#define OPENXR_HPP_NAMESPACE xr
#endif  // !OPENXR_HPP_NAMESPACE
namespace OPENXR_HPP_NAMESPACE {
/*!
 * @brief XrDuration wrapper class
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrDuration>
 *
 * @xrentity{XrDuration}
 * @ingroup wrappers
 */
class Duration {
public:
  /*!
   * @name Constructors, assignment, and conversions
   * @{
   */
  //! Default constructor.
  OPENXR_HPP_CONSTEXPR Duration() noexcept = default;

  //! Explicit constructor from raw XrDuration value
  OPENXR_HPP_CONSTEXPR explicit Duration(XrDuration v) noexcept : val_(v) {}

  //! @}
  /*!
   * @name Raw XrDuration manipulation
   * @{
   */
  //! Gets the raw XrDuration value.
  OPENXR_HPP_CONSTEXPR XrDuration get() const noexcept { return val_; }
  /*!
   * @brief Clears this value, then returns the address of the raw XrDuration value,
   * for use in creation/assignment.
   */
  XrDuration *put(bool clear = true) noexcept {
    if (clear) val_ = 0;
    return &val_;
  }
  //! @}

  //! Add a Duration to the current Duration
  Duration &operator+=(Duration d) noexcept {
    val_ += d.val_;
    return *this;
  }

  //! Subtract a Duration from the current Duration
  Duration &operator-=(Duration d) noexcept {
    val_ -= d.val_;
    return *this;
  }

  //! For timeouts, indicates the timeout is immediate
  static OPENXR_HPP_CONSTEXPR Duration noDuration() noexcept { return Duration{XR_NO_DURATION}; }

  //! For timeouts, indicates the timeout never occurs.
  static OPENXR_HPP_CONSTEXPR Duration infinite() noexcept {
    return Duration{XR_INFINITE_DURATION};
  }

  //! For haptic vibration, the shortest pulse possible for the device
  static OPENXR_HPP_CONSTEXPR Duration minHaptic() noexcept {
    return Duration{XR_MIN_HAPTIC_DURATION};
  }

private:
  XrDuration val_{};
};

static_assert(sizeof(XrDuration) == sizeof(Duration),
              "Original type and wrapper have different size!");

/*!
 * @brief Free function for getting the raw XrDuration from an Duration value.
 *
 * @found_by_adl
 * @see Duration::get()
 * @relates Duration
 * @ingroup utility_accessors
 */
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE XrDuration get(Duration v) noexcept { return v.get(); }
/*!
 * @brief Free function for clearing (by default) and getting the address of the raw XrDuration from
 * an Duration value.
 *
 * @found_by_adl
 * @see Duration::put( )
 * @relates Duration
 * @ingroup utility_accessors
 */
static OPENXR_HPP_INLINE XrDuration *put(Duration &v, bool clear = true) noexcept {
  return v.put(clear);
}
//! @brief `<` comparison between Duration values.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator<(Duration lhs, Duration rhs) noexcept {
  return lhs.get() < rhs.get();
}
//! @brief `>` comparison between Duration values.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator>(Duration lhs, Duration rhs) noexcept {
  return lhs.get() > rhs.get();
}
//! @brief `<=` comparison between Duration values.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator<=(Duration lhs, Duration rhs) noexcept {
  return lhs.get() <= rhs.get();
}
//! @brief `>=` comparison between Duration values.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator>=(Duration lhs, Duration rhs) noexcept {
  return lhs.get() >= rhs.get();
}
//! @brief `==` comparison between Duration values.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator==(Duration lhs, Duration rhs) noexcept {
  return lhs.get() == rhs.get();
}
//! @brief `!=` comparison between Duration values.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator!=(Duration lhs, Duration rhs) noexcept {
  return lhs.get() != rhs.get();
}
//! @brief `<` comparison between Duration and raw XrDuration.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator<(Duration lhs, XrDuration rhs) noexcept {
  return lhs.get() < rhs;
}
//! @brief `<` comparison between raw XrDuration and Duration.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator<(XrDuration lhs, Duration rhs) noexcept {
  return lhs < rhs.get();
}
//! @brief `>` comparison between Duration and raw XrDuration.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator>(Duration lhs, XrDuration rhs) noexcept {
  return lhs.get() > rhs;
}
//! @brief `>` comparison between raw XrDuration and Duration.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator>(XrDuration lhs, Duration rhs) noexcept {
  return lhs > rhs.get();
}
//! @brief `<=` comparison between Duration and raw XrDuration.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator<=(Duration lhs, XrDuration rhs) noexcept {
  return lhs.get() <= rhs;
}
//! @brief `<=` comparison between raw XrDuration and Duration.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator<=(XrDuration lhs, Duration rhs) noexcept {
  return lhs <= rhs.get();
}
//! @brief `>=` comparison between Duration and raw XrDuration.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator>=(Duration lhs, XrDuration rhs) noexcept {
  return lhs.get() >= rhs;
}
//! @brief `>=` comparison between raw XrDuration and Duration.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator>=(XrDuration lhs, Duration rhs) noexcept {
  return lhs >= rhs.get();
}
//! @brief `==` comparison between Duration and raw XrDuration.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator==(Duration lhs, XrDuration rhs) noexcept {
  return lhs.get() == rhs;
}
//! @brief `==` comparison between raw XrDuration and Duration.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator==(XrDuration lhs, Duration rhs) noexcept {
  return lhs == rhs.get();
}
//! @brief `!=` comparison between Duration and raw XrDuration.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator!=(Duration lhs, XrDuration rhs) noexcept {
  return lhs.get() != rhs;
}
//! @brief `!=` comparison between raw XrDuration and Duration.
//! @relates Duration
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE bool operator!=(XrDuration lhs, Duration rhs) noexcept {
  return lhs != rhs.get();
}
//! Add two Duration values
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE Duration operator+(Duration lhs, Duration rhs) noexcept {
  return Duration{lhs.get() + rhs.get()};
}

//! Subtract two Duration values
OPENXR_HPP_CONSTEXPR OPENXR_HPP_INLINE Duration operator-(Duration lhs, Duration rhs) noexcept {
  return Duration{lhs.get() - rhs.get()};
}
}  // namespace OPENXR_HPP_NAMESPACE

#endif  // ifndef OPENXR_DURATION_HPP_
