// *********** THIS FILE IS GENERATED - DO NOT EDIT ***********
//     See cpp_generator.py for modifications
// ************************************************************

/*
** Copyright (c) 2017-2021 The Khronos Group Inc.
** Copyright (c) 2019-2021 Collabora, Ltd.
**
** Licensed under the Apache License, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
**
**     http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
**
** ---- Exceptions to the Apache 2.0 License: ----
**
** As an exception, if you use this Software to generate code and portions of
** this Software are embedded into the generated code as a result, you may
** redistribute such product without providing attribution as would otherwise
** be required by Sections 4(a), 4(b) and 4(d) of the License.
**
** In addition, if you combine or link code generated by this Software with
** software that is licensed under the GPLv2 or the LGPL v2.0 or 2.1
** ("`Combined Software`") and if a court of competent jurisdiction determines
** that the patent provision (Section 3), the indemnity provision (Section 9)
** or other Section of the License conflicts with the conditions of the
** applicable GPL or LGPL license, you may retroactively and prospectively
** choose to deem waived or otherwise exclude such Section(s) of the License,
** but only in their entirety and only with respect to the Combined Software.
**
*/

/*
** This header is generated from the Khronos OpenXR XML API Registry.
**
*/
#ifndef OPENXR_FLAGS_HPP_
#define OPENXR_FLAGS_HPP_
/**
 * @file
 * @brief C++ projections of OpenXR flag (bitmask) types.
 *
 * @see openxr_enums.hpp
 * @ingroup flags
 */

#include <openxr/openxr.h>

#ifdef OPENXR_HPP_DOXYGEN
#include <openxr/openxr_platform.h>
#endif

#if !defined(OPENXR_HPP_ASSERT)
#include <cassert>
#define OPENXR_HPP_ASSERT assert
#endif

// 32-bit OpenXR is not typesafe for handles, so don't allow copy constructors
// on this platform by default. To enable this feature on 32-bit platforms
// please define OPENXR_HPP_TYPESAFE_CONVERSION
#if defined(__LP64__) || defined(_WIN64) || (defined(__x86_64__) && !defined(__ILP32__)) || \
    defined(_M_X64) || defined(__ia64) || defined(_M_IA64) || defined(__aarch64__) ||       \
    defined(__powerpc64__)
#if !defined(OPENXR_HPP_TYPESAFE_CONVERSION)
#define OPENXR_HPP_TYPESAFE_CONVERSION
#endif
#endif

#if !defined(OPENXR_HPP_INLINE)
#if defined(__clang___)
#if __has_attribute(always_inline)
#define OPENXR_HPP_INLINE __attribute__((always_inline)) __inline__
#else
#define OPENXR_HPP_INLINE inline
#endif
#elif defined(__GNUC__)
#define OPENXR_HPP_INLINE __attribute__((always_inline)) __inline__
#elif defined(_MSC_VER)
#define OPENXR_HPP_INLINE inline
#else
#define OPENXR_HPP_INLINE inline
#endif
#endif  // !OPENXR_HPP_INLINE

#if !defined(OPENXR_HPP_CONSTEXPR)
#if defined(_MSC_VER) && (_MSC_VER <= 1800)
#define OPENXR_HPP_CONSTEXPR
#else
#define OPENXR_HPP_CONSTEXPR constexpr
#endif
#endif  // !OPENXR_HPP_CONSTEXPR

#if !defined(OPENXR_HPP_SWITCH_CONSTEXPR)
//! @todo set this to constexpr in c++14
#define OPENXR_HPP_SWITCH_CONSTEXPR
#endif  // !OPENXR_HPP_SWITCH_CONSTEXPR

#if !defined(OPENXR_HPP_NAMESPACE)
#define OPENXR_HPP_NAMESPACE xr
#endif  // !OPENXR_HPP_NAMESPACE

#if !defined(OPENXR_HPP_STRINGIFY)
#define OPENXR_HPP_STRINGIFY2(text) #text
#define OPENXR_HPP_STRINGIFY(text) OPENXR_HPP_STRINGIFY2(text)
#define OPENXR_HPP_NAMESPACE_STRING OPENXR_HPP_STRINGIFY(OPENXR_HPP_NAMESPACE)
#endif  // !OPENXR_HPP_STRINGIFY

namespace OPENXR_HPP_NAMESPACE {

/**
 * @brief Template type for bit flag projection
 *
 * @tparam BitType The projected enum that contains the bits
 * @tparam MaskType The type of the combined flags, typically the default, XrFlags64.
 */
template <typename BitType, typename MaskType = XrFlags64>
class Flags {
public:
  //! Default constructor
  OPENXR_HPP_CONSTEXPR Flags() : m_mask(0) {}

  //! Implicit constructor from a single bit
  Flags(BitType bit) : m_mask(static_cast<MaskType>(bit)) {}

  //! Copy constructor
  Flags(Flags const &rhs) = default;

  //! Copy assignment
  Flags &operator=(Flags const &rhs) = default;

  //! Explicit constructor from flags value
  explicit Flags(MaskType flags) : m_mask(flags) {}

  //! OR update operator - commonly used for combining flags
  Flags &operator|=(Flags const &rhs) {
    m_mask |= rhs.m_mask;
    return *this;
  }

  //! AND update operator
  Flags &operator&=(Flags const &rhs) {
    m_mask &= rhs.m_mask;
    return *this;
  }

  //! XOR update operator
  Flags &operator^=(Flags const &rhs) {
    m_mask ^= rhs.m_mask;
    return *this;
  }

  //! OR operator, often used for combining flags.
  Flags operator|(Flags const &rhs) const {
    Flags result(*this);
    result |= rhs;
    return result;
  }

  //! AND operator, often used for testing the value of certain bits.
  Flags operator&(Flags const &rhs) const {
    Flags result(*this);
    result &= rhs;
    return result;
  }

  //! XOR operator
  Flags operator^(Flags const &rhs) const {
    Flags result(*this);
    result ^= rhs;
    return result;
  }

  //! Unary negation: true if all bits were false.
  bool operator!() const { return !m_mask; }

  //! Bitwise negation (complement) operator
  Flags operator~() const {
    Flags result(*this);
    result.m_mask ^= static_cast<MaskType>(BitType::AllBits);
    return result;
  }

  //! Accessor for contained value
  MaskType get() const noexcept { return m_mask; }

  //! Equality comparison
  bool operator==(Flags const &rhs) const { return m_mask == rhs.m_mask; }

  //! Inequality comparison
  bool operator!=(Flags const &rhs) const { return m_mask != rhs.m_mask; }

  //! Equality comparison, mainly intended for compare to 0
  bool operator==(int rhs) const { return m_mask == static_cast<MaskType>(rhs); }

  //! Inequality comparison, mainly intended for compare to 0
  bool operator!=(int rhs) const { return m_mask != static_cast<MaskType>(rhs); }

  //! Explicit bool conversion: true if any bits are true.
  explicit operator bool() const { return !!m_mask; }

  //! Explicit conversion operator to the underlying mask type.
  explicit operator MaskType() const { return m_mask; }

private:
  MaskType m_mask;
};

/**
 * @brief Bitwise OR between a Flags<> value and a single bit.
 *
 * @tparam BitType The projected bit type
 * @param bit The single bit
 * @param flags The Flags<> value
 * @return Flags<BitType>
 *
 * @relates Flags
 */
template <typename BitType, typename MaskType>
Flags<BitType, MaskType> operator|(BitType bit, Flags<BitType, MaskType> const &flags) {
  return flags | bit;
}

/**
 * @brief Bitwise AND between a Flags<> value and a single bit.
 *
 * @tparam BitType The projected bit type
 * @param bit The single bit
 * @param flags The Flags<> value
 * @return Flags<BitType>
 *
 * @relates Flags
 */
template <typename BitType, typename MaskType>
Flags<BitType, MaskType> operator&(BitType bit, Flags<BitType, MaskType> const &flags) {
  return flags & bit;
}

/**
 * @brief Bitwise XOR between a Flags<> value and a single bit.
 *
 * @tparam BitType The projected bit type
 * @param bit The single bit
 * @param flags The Flags<> value
 * @return Flags<BitType>
 *
 * @relates Flags
 */
template <typename BitType, typename MaskType>
Flags<BitType, MaskType> operator^(BitType bit, Flags<BitType, MaskType> const &flags) {
  return flags ^ bit;
}

}  // namespace OPENXR_HPP_NAMESPACE
namespace OPENXR_HPP_NAMESPACE {

/*!
 * @defgroup flags Flags
 * @brief C++ flags classes corresponding to OpenXR C flags and flagbits, plus associated utility
 * functions.
 * @ingroup wrappers
 * @{
 */

/*!
 * @brief Flag bits for XrInstanceCreateFlags
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrInstanceCreateFlagBits>
 * @xrentity{XrInstanceCreateFlagBits}
 * @see InstanceCreateFlags
 */
enum class InstanceCreateFlagBits : XrFlags64 { None = 0, AllBits = 0 };

/*!
 * @brief Flags class projection of XrInstanceCreateFlags
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrInstanceCreateFlags>
 * @xrentity{XrInstanceCreateFlagBits}
 * @see InstanceCreateFlagBits, xr::Flags
 */
using InstanceCreateFlags = Flags<InstanceCreateFlagBits, XrInstanceCreateFlags>;

/*!
 * @brief Bitwise OR operator between two InstanceCreateFlagBits flag bits.
 * @see InstanceCreateFlagBits, InstanceCreateFlags, xr::Flags
 */
OPENXR_HPP_INLINE InstanceCreateFlags operator|(InstanceCreateFlagBits bit0,
                                                InstanceCreateFlagBits bit1) {
  return InstanceCreateFlags(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a InstanceCreateFlagBits flag bit.
 * @see InstanceCreateFlagBits, InstanceCreateFlags, xr::Flags
 */
OPENXR_HPP_INLINE InstanceCreateFlags operator~(InstanceCreateFlagBits bits) {
  return ~(InstanceCreateFlags(bits));
}

/*!
 * @brief Flag bits for XrSessionCreateFlags
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrSessionCreateFlagBits>
 * @xrentity{XrSessionCreateFlagBits}
 * @see SessionCreateFlags
 */
enum class SessionCreateFlagBits : XrFlags64 { None = 0, AllBits = 0 };

/*!
 * @brief Flags class projection of XrSessionCreateFlags
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrSessionCreateFlags>
 * @xrentity{XrSessionCreateFlagBits}
 * @see SessionCreateFlagBits, xr::Flags
 */
using SessionCreateFlags = Flags<SessionCreateFlagBits, XrSessionCreateFlags>;

/*!
 * @brief Bitwise OR operator between two SessionCreateFlagBits flag bits.
 * @see SessionCreateFlagBits, SessionCreateFlags, xr::Flags
 */
OPENXR_HPP_INLINE SessionCreateFlags operator|(SessionCreateFlagBits bit0,
                                               SessionCreateFlagBits bit1) {
  return SessionCreateFlags(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a SessionCreateFlagBits flag bit.
 * @see SessionCreateFlagBits, SessionCreateFlags, xr::Flags
 */
OPENXR_HPP_INLINE SessionCreateFlags operator~(SessionCreateFlagBits bits) {
  return ~(SessionCreateFlags(bits));
}

/*!
 * @brief Flag bits for XrSpaceVelocityFlags
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrSpaceVelocityFlagBits>
 * @xrentity{XrSpaceVelocityFlagBits}
 * @see SpaceVelocityFlags
 */
enum class SpaceVelocityFlagBits : XrFlags64 {
  None = 0,
  LinearValid = XR_SPACE_VELOCITY_LINEAR_VALID_BIT,
  AngularValid = XR_SPACE_VELOCITY_ANGULAR_VALID_BIT,
  AllBits = XR_SPACE_VELOCITY_LINEAR_VALID_BIT | XR_SPACE_VELOCITY_ANGULAR_VALID_BIT
};

/*!
 * @brief Flags class projection of XrSpaceVelocityFlags
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrSpaceVelocityFlags>
 * @xrentity{XrSpaceVelocityFlagBits}
 * @see SpaceVelocityFlagBits, xr::Flags
 */
using SpaceVelocityFlags = Flags<SpaceVelocityFlagBits, XrSpaceVelocityFlags>;

/*!
 * @brief Bitwise OR operator between two SpaceVelocityFlagBits flag bits.
 * @see SpaceVelocityFlagBits, SpaceVelocityFlags, xr::Flags
 */
OPENXR_HPP_INLINE SpaceVelocityFlags operator|(SpaceVelocityFlagBits bit0,
                                               SpaceVelocityFlagBits bit1) {
  return SpaceVelocityFlags(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a SpaceVelocityFlagBits flag bit.
 * @see SpaceVelocityFlagBits, SpaceVelocityFlags, xr::Flags
 */
OPENXR_HPP_INLINE SpaceVelocityFlags operator~(SpaceVelocityFlagBits bits) {
  return ~(SpaceVelocityFlags(bits));
}

/*!
 * @brief Flag bits for XrSpaceLocationFlags
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrSpaceLocationFlagBits>
 * @xrentity{XrSpaceLocationFlagBits}
 * @see SpaceLocationFlags
 */
enum class SpaceLocationFlagBits : XrFlags64 {
  None = 0,
  OrientationValid = XR_SPACE_LOCATION_ORIENTATION_VALID_BIT,
  PositionValid = XR_SPACE_LOCATION_POSITION_VALID_BIT,
  OrientationTracked = XR_SPACE_LOCATION_ORIENTATION_TRACKED_BIT,
  PositionTracked = XR_SPACE_LOCATION_POSITION_TRACKED_BIT,
  AllBits = XR_SPACE_LOCATION_ORIENTATION_VALID_BIT | XR_SPACE_LOCATION_POSITION_VALID_BIT |
            XR_SPACE_LOCATION_ORIENTATION_TRACKED_BIT | XR_SPACE_LOCATION_POSITION_TRACKED_BIT
};

/*!
 * @brief Flags class projection of XrSpaceLocationFlags
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrSpaceLocationFlags>
 * @xrentity{XrSpaceLocationFlagBits}
 * @see SpaceLocationFlagBits, xr::Flags
 */
using SpaceLocationFlags = Flags<SpaceLocationFlagBits, XrSpaceLocationFlags>;

/*!
 * @brief Bitwise OR operator between two SpaceLocationFlagBits flag bits.
 * @see SpaceLocationFlagBits, SpaceLocationFlags, xr::Flags
 */
OPENXR_HPP_INLINE SpaceLocationFlags operator|(SpaceLocationFlagBits bit0,
                                               SpaceLocationFlagBits bit1) {
  return SpaceLocationFlags(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a SpaceLocationFlagBits flag bit.
 * @see SpaceLocationFlagBits, SpaceLocationFlags, xr::Flags
 */
OPENXR_HPP_INLINE SpaceLocationFlags operator~(SpaceLocationFlagBits bits) {
  return ~(SpaceLocationFlags(bits));
}

/*!
 * @brief Flag bits for XrSwapchainCreateFlags
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrSwapchainCreateFlagBits>
 * @xrentity{XrSwapchainCreateFlagBits}
 * @see SwapchainCreateFlags
 */
enum class SwapchainCreateFlagBits : XrFlags64 {
  None = 0,
  ProtectedContent = XR_SWAPCHAIN_CREATE_PROTECTED_CONTENT_BIT,
  StaticImage = XR_SWAPCHAIN_CREATE_STATIC_IMAGE_BIT,
  AllBits = XR_SWAPCHAIN_CREATE_PROTECTED_CONTENT_BIT | XR_SWAPCHAIN_CREATE_STATIC_IMAGE_BIT
};

/*!
 * @brief Flags class projection of XrSwapchainCreateFlags
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrSwapchainCreateFlags>
 * @xrentity{XrSwapchainCreateFlagBits}
 * @see SwapchainCreateFlagBits, xr::Flags
 */
using SwapchainCreateFlags = Flags<SwapchainCreateFlagBits, XrSwapchainCreateFlags>;

/*!
 * @brief Bitwise OR operator between two SwapchainCreateFlagBits flag bits.
 * @see SwapchainCreateFlagBits, SwapchainCreateFlags, xr::Flags
 */
OPENXR_HPP_INLINE SwapchainCreateFlags operator|(SwapchainCreateFlagBits bit0,
                                                 SwapchainCreateFlagBits bit1) {
  return SwapchainCreateFlags(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a SwapchainCreateFlagBits flag bit.
 * @see SwapchainCreateFlagBits, SwapchainCreateFlags, xr::Flags
 */
OPENXR_HPP_INLINE SwapchainCreateFlags operator~(SwapchainCreateFlagBits bits) {
  return ~(SwapchainCreateFlags(bits));
}

/*!
 * @brief Flag bits for XrSwapchainUsageFlags
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrSwapchainUsageFlagBits>
 * @xrentity{XrSwapchainUsageFlagBits}
 * @see SwapchainUsageFlags
 */
enum class SwapchainUsageFlagBits : XrFlags64 {
  None = 0,
  ColorAttachment = XR_SWAPCHAIN_USAGE_COLOR_ATTACHMENT_BIT,
  DepthStencilAttachment = XR_SWAPCHAIN_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT,
  UnorderedAccess = XR_SWAPCHAIN_USAGE_UNORDERED_ACCESS_BIT,
  TransferSrc = XR_SWAPCHAIN_USAGE_TRANSFER_SRC_BIT,
  TransferDst = XR_SWAPCHAIN_USAGE_TRANSFER_DST_BIT,
  Sampled = XR_SWAPCHAIN_USAGE_SAMPLED_BIT,
  MutableFormat = XR_SWAPCHAIN_USAGE_MUTABLE_FORMAT_BIT,
  InputAttachmentBitMND = XR_SWAPCHAIN_USAGE_INPUT_ATTACHMENT_BIT_MND,
  InputAttachmentBitKHR = XR_SWAPCHAIN_USAGE_INPUT_ATTACHMENT_BIT_KHR,
  AllBits = XR_SWAPCHAIN_USAGE_COLOR_ATTACHMENT_BIT |
            XR_SWAPCHAIN_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT |
            XR_SWAPCHAIN_USAGE_UNORDERED_ACCESS_BIT | XR_SWAPCHAIN_USAGE_TRANSFER_SRC_BIT |
            XR_SWAPCHAIN_USAGE_TRANSFER_DST_BIT | XR_SWAPCHAIN_USAGE_SAMPLED_BIT |
            XR_SWAPCHAIN_USAGE_MUTABLE_FORMAT_BIT | XR_SWAPCHAIN_USAGE_INPUT_ATTACHMENT_BIT_MND |
            XR_SWAPCHAIN_USAGE_INPUT_ATTACHMENT_BIT_KHR
};

/*!
 * @brief Flags class projection of XrSwapchainUsageFlags
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrSwapchainUsageFlags>
 * @xrentity{XrSwapchainUsageFlagBits}
 * @see SwapchainUsageFlagBits, xr::Flags
 */
using SwapchainUsageFlags = Flags<SwapchainUsageFlagBits, XrSwapchainUsageFlags>;

/*!
 * @brief Bitwise OR operator between two SwapchainUsageFlagBits flag bits.
 * @see SwapchainUsageFlagBits, SwapchainUsageFlags, xr::Flags
 */
OPENXR_HPP_INLINE SwapchainUsageFlags operator|(SwapchainUsageFlagBits bit0,
                                                SwapchainUsageFlagBits bit1) {
  return SwapchainUsageFlags(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a SwapchainUsageFlagBits flag bit.
 * @see SwapchainUsageFlagBits, SwapchainUsageFlags, xr::Flags
 */
OPENXR_HPP_INLINE SwapchainUsageFlags operator~(SwapchainUsageFlagBits bits) {
  return ~(SwapchainUsageFlags(bits));
}

/*!
 * @brief Flag bits for XrCompositionLayerFlags
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrCompositionLayerFlagBits>
 * @xrentity{XrCompositionLayerFlagBits}
 * @see CompositionLayerFlags
 */
enum class CompositionLayerFlagBits : XrFlags64 {
  None = 0,
  CorrectChromaticAberration = XR_COMPOSITION_LAYER_CORRECT_CHROMATIC_ABERRATION_BIT,
  BlendTextureSourceAlpha = XR_COMPOSITION_LAYER_BLEND_TEXTURE_SOURCE_ALPHA_BIT,
  UnpremultipliedAlpha = XR_COMPOSITION_LAYER_UNPREMULTIPLIED_ALPHA_BIT,
  AllBits = XR_COMPOSITION_LAYER_CORRECT_CHROMATIC_ABERRATION_BIT |
            XR_COMPOSITION_LAYER_BLEND_TEXTURE_SOURCE_ALPHA_BIT |
            XR_COMPOSITION_LAYER_UNPREMULTIPLIED_ALPHA_BIT
};

/*!
 * @brief Flags class projection of XrCompositionLayerFlags
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrCompositionLayerFlags>
 * @xrentity{XrCompositionLayerFlagBits}
 * @see CompositionLayerFlagBits, xr::Flags
 */
using CompositionLayerFlags = Flags<CompositionLayerFlagBits, XrCompositionLayerFlags>;

/*!
 * @brief Bitwise OR operator between two CompositionLayerFlagBits flag bits.
 * @see CompositionLayerFlagBits, CompositionLayerFlags, xr::Flags
 */
OPENXR_HPP_INLINE CompositionLayerFlags operator|(CompositionLayerFlagBits bit0,
                                                  CompositionLayerFlagBits bit1) {
  return CompositionLayerFlags(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a CompositionLayerFlagBits flag bit.
 * @see CompositionLayerFlagBits, CompositionLayerFlags, xr::Flags
 */
OPENXR_HPP_INLINE CompositionLayerFlags operator~(CompositionLayerFlagBits bits) {
  return ~(CompositionLayerFlags(bits));
}

/*!
 * @brief Flag bits for XrViewStateFlags
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrViewStateFlagBits>
 * @xrentity{XrViewStateFlagBits}
 * @see ViewStateFlags
 */
enum class ViewStateFlagBits : XrFlags64 {
  None = 0,
  OrientationValid = XR_VIEW_STATE_ORIENTATION_VALID_BIT,
  PositionValid = XR_VIEW_STATE_POSITION_VALID_BIT,
  OrientationTracked = XR_VIEW_STATE_ORIENTATION_TRACKED_BIT,
  PositionTracked = XR_VIEW_STATE_POSITION_TRACKED_BIT,
  AllBits = XR_VIEW_STATE_ORIENTATION_VALID_BIT | XR_VIEW_STATE_POSITION_VALID_BIT |
            XR_VIEW_STATE_ORIENTATION_TRACKED_BIT | XR_VIEW_STATE_POSITION_TRACKED_BIT
};

/*!
 * @brief Flags class projection of XrViewStateFlags
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrViewStateFlags>
 * @xrentity{XrViewStateFlagBits}
 * @see ViewStateFlagBits, xr::Flags
 */
using ViewStateFlags = Flags<ViewStateFlagBits, XrViewStateFlags>;

/*!
 * @brief Bitwise OR operator between two ViewStateFlagBits flag bits.
 * @see ViewStateFlagBits, ViewStateFlags, xr::Flags
 */
OPENXR_HPP_INLINE ViewStateFlags operator|(ViewStateFlagBits bit0, ViewStateFlagBits bit1) {
  return ViewStateFlags(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a ViewStateFlagBits flag bit.
 * @see ViewStateFlagBits, ViewStateFlags, xr::Flags
 */
OPENXR_HPP_INLINE ViewStateFlags operator~(ViewStateFlagBits bits) {
  return ~(ViewStateFlags(bits));
}

/*!
 * @brief Flag bits for XrInputSourceLocalizedNameFlags
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrInputSourceLocalizedNameFlagBits>
 * @xrentity{XrInputSourceLocalizedNameFlagBits}
 * @see InputSourceLocalizedNameFlags
 */
enum class InputSourceLocalizedNameFlagBits : XrFlags64 {
  None = 0,
  UserPath = XR_INPUT_SOURCE_LOCALIZED_NAME_USER_PATH_BIT,
  InteractionProfile = XR_INPUT_SOURCE_LOCALIZED_NAME_INTERACTION_PROFILE_BIT,
  Component = XR_INPUT_SOURCE_LOCALIZED_NAME_COMPONENT_BIT,
  AllBits = XR_INPUT_SOURCE_LOCALIZED_NAME_USER_PATH_BIT |
            XR_INPUT_SOURCE_LOCALIZED_NAME_INTERACTION_PROFILE_BIT |
            XR_INPUT_SOURCE_LOCALIZED_NAME_COMPONENT_BIT
};

/*!
 * @brief Flags class projection of XrInputSourceLocalizedNameFlags
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrInputSourceLocalizedNameFlags>
 * @xrentity{XrInputSourceLocalizedNameFlagBits}
 * @see InputSourceLocalizedNameFlagBits, xr::Flags
 */
using InputSourceLocalizedNameFlags =
    Flags<InputSourceLocalizedNameFlagBits, XrInputSourceLocalizedNameFlags>;

/*!
 * @brief Bitwise OR operator between two InputSourceLocalizedNameFlagBits flag bits.
 * @see InputSourceLocalizedNameFlagBits, InputSourceLocalizedNameFlags, xr::Flags
 */
OPENXR_HPP_INLINE InputSourceLocalizedNameFlags operator|(InputSourceLocalizedNameFlagBits bit0,
                                                          InputSourceLocalizedNameFlagBits bit1) {
  return InputSourceLocalizedNameFlags(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a InputSourceLocalizedNameFlagBits flag bit.
 * @see InputSourceLocalizedNameFlagBits, InputSourceLocalizedNameFlags, xr::Flags
 */
OPENXR_HPP_INLINE InputSourceLocalizedNameFlags operator~(InputSourceLocalizedNameFlagBits bits) {
  return ~(InputSourceLocalizedNameFlags(bits));
}

#ifdef XR_KHR_vulkan_enable2
#if defined(XR_USE_GRAPHICS_API_VULKAN)
/*!
 * @brief Flag bits for XrVulkanInstanceCreateFlagsKHR
 *
 * Provided by the `XR_KHR_vulkan_enable2` extension.
 * Be sure to include `<openxr_platform.h>` before including this header to use it.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrVulkanInstanceCreateFlagBitsKHR>
 * @xrentity{XrVulkanInstanceCreateFlagBitsKHR}
 * @see VulkanInstanceCreateFlagsKHR
 */
enum class VulkanInstanceCreateFlagBitsKHR : XrFlags64 { None = 0, AllBits = 0 };

/*!
 * @brief Flags class projection of XrVulkanInstanceCreateFlagsKHR
 *
 * Provided by the `XR_KHR_vulkan_enable2` extension.
 * Be sure to include `<openxr_platform.h>` before including this header to use it.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrVulkanInstanceCreateFlagsKHR>
 * @xrentity{XrVulkanInstanceCreateFlagBitsKHR}
 * @see VulkanInstanceCreateFlagBitsKHR, xr::Flags
 */
using VulkanInstanceCreateFlagsKHR =
    Flags<VulkanInstanceCreateFlagBitsKHR, XrVulkanInstanceCreateFlagsKHR>;

/*!
 * @brief Bitwise OR operator between two VulkanInstanceCreateFlagBitsKHR flag bits.
 * @see VulkanInstanceCreateFlagBitsKHR, VulkanInstanceCreateFlagsKHR, xr::Flags
 */
OPENXR_HPP_INLINE VulkanInstanceCreateFlagsKHR operator|(VulkanInstanceCreateFlagBitsKHR bit0,
                                                         VulkanInstanceCreateFlagBitsKHR bit1) {
  return VulkanInstanceCreateFlagsKHR(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a VulkanInstanceCreateFlagBitsKHR flag bit.
 * @see VulkanInstanceCreateFlagBitsKHR, VulkanInstanceCreateFlagsKHR, xr::Flags
 */
OPENXR_HPP_INLINE VulkanInstanceCreateFlagsKHR operator~(VulkanInstanceCreateFlagBitsKHR bits) {
  return ~(VulkanInstanceCreateFlagsKHR(bits));
}

#endif  // defined(XR_USE_GRAPHICS_API_VULKAN)
#endif  // XR_KHR_vulkan_enable2

#ifdef XR_KHR_vulkan_enable2
#if defined(XR_USE_GRAPHICS_API_VULKAN)
/*!
 * @brief Flag bits for XrVulkanDeviceCreateFlagsKHR
 *
 * Provided by the `XR_KHR_vulkan_enable2` extension.
 * Be sure to include `<openxr_platform.h>` before including this header to use it.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrVulkanDeviceCreateFlagBitsKHR>
 * @xrentity{XrVulkanDeviceCreateFlagBitsKHR}
 * @see VulkanDeviceCreateFlagsKHR
 */
enum class VulkanDeviceCreateFlagBitsKHR : XrFlags64 { None = 0, AllBits = 0 };

/*!
 * @brief Flags class projection of XrVulkanDeviceCreateFlagsKHR
 *
 * Provided by the `XR_KHR_vulkan_enable2` extension.
 * Be sure to include `<openxr_platform.h>` before including this header to use it.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrVulkanDeviceCreateFlagsKHR>
 * @xrentity{XrVulkanDeviceCreateFlagBitsKHR}
 * @see VulkanDeviceCreateFlagBitsKHR, xr::Flags
 */
using VulkanDeviceCreateFlagsKHR =
    Flags<VulkanDeviceCreateFlagBitsKHR, XrVulkanDeviceCreateFlagsKHR>;

/*!
 * @brief Bitwise OR operator between two VulkanDeviceCreateFlagBitsKHR flag bits.
 * @see VulkanDeviceCreateFlagBitsKHR, VulkanDeviceCreateFlagsKHR, xr::Flags
 */
OPENXR_HPP_INLINE VulkanDeviceCreateFlagsKHR operator|(VulkanDeviceCreateFlagBitsKHR bit0,
                                                       VulkanDeviceCreateFlagBitsKHR bit1) {
  return VulkanDeviceCreateFlagsKHR(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a VulkanDeviceCreateFlagBitsKHR flag bit.
 * @see VulkanDeviceCreateFlagBitsKHR, VulkanDeviceCreateFlagsKHR, xr::Flags
 */
OPENXR_HPP_INLINE VulkanDeviceCreateFlagsKHR operator~(VulkanDeviceCreateFlagBitsKHR bits) {
  return ~(VulkanDeviceCreateFlagsKHR(bits));
}

#endif  // defined(XR_USE_GRAPHICS_API_VULKAN)
#endif  // XR_KHR_vulkan_enable2

#ifdef XR_EXT_debug_utils
/*!
 * @brief Flag bits for XrDebugUtilsMessageSeverityFlagsEXT
 *
 * Provided by the `XR_EXT_debug_utils` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrDebugUtilsMessageSeverityFlagBitsEXT>
 * @xrentity{XrDebugUtilsMessageSeverityFlagBitsEXT}
 * @see DebugUtilsMessageSeverityFlagsEXT
 */
enum class DebugUtilsMessageSeverityFlagBitsEXT : XrFlags64 {
  None = 0,
  Verbose = XR_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT,
  Info = XR_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT,
  Warning = XR_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT,
  Error = XR_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT,
  AllBits = XR_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT |
            XR_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT |
            XR_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT |
            XR_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT
};

/*!
 * @brief Flags class projection of XrDebugUtilsMessageSeverityFlagsEXT
 *
 * Provided by the `XR_EXT_debug_utils` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrDebugUtilsMessageSeverityFlagsEXT>
 * @xrentity{XrDebugUtilsMessageSeverityFlagBitsEXT}
 * @see DebugUtilsMessageSeverityFlagBitsEXT, xr::Flags
 */
using DebugUtilsMessageSeverityFlagsEXT =
    Flags<DebugUtilsMessageSeverityFlagBitsEXT, XrDebugUtilsMessageSeverityFlagsEXT>;

/*!
 * @brief Bitwise OR operator between two DebugUtilsMessageSeverityFlagBitsEXT flag bits.
 * @see DebugUtilsMessageSeverityFlagBitsEXT, DebugUtilsMessageSeverityFlagsEXT, xr::Flags
 */
OPENXR_HPP_INLINE DebugUtilsMessageSeverityFlagsEXT
operator|(DebugUtilsMessageSeverityFlagBitsEXT bit0, DebugUtilsMessageSeverityFlagBitsEXT bit1) {
  return DebugUtilsMessageSeverityFlagsEXT(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a DebugUtilsMessageSeverityFlagBitsEXT flag bit.
 * @see DebugUtilsMessageSeverityFlagBitsEXT, DebugUtilsMessageSeverityFlagsEXT, xr::Flags
 */
OPENXR_HPP_INLINE DebugUtilsMessageSeverityFlagsEXT
operator~(DebugUtilsMessageSeverityFlagBitsEXT bits) {
  return ~(DebugUtilsMessageSeverityFlagsEXT(bits));
}

#endif  // XR_EXT_debug_utils

#ifdef XR_EXT_debug_utils
/*!
 * @brief Flag bits for XrDebugUtilsMessageTypeFlagsEXT
 *
 * Provided by the `XR_EXT_debug_utils` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrDebugUtilsMessageTypeFlagBitsEXT>
 * @xrentity{XrDebugUtilsMessageTypeFlagBitsEXT}
 * @see DebugUtilsMessageTypeFlagsEXT
 */
enum class DebugUtilsMessageTypeFlagBitsEXT : XrFlags64 {
  None = 0,
  General = XR_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT,
  Validation = XR_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT,
  Performance = XR_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT,
  Conformance = XR_DEBUG_UTILS_MESSAGE_TYPE_CONFORMANCE_BIT_EXT,
  AllBits = XR_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT |
            XR_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT |
            XR_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT |
            XR_DEBUG_UTILS_MESSAGE_TYPE_CONFORMANCE_BIT_EXT
};

/*!
 * @brief Flags class projection of XrDebugUtilsMessageTypeFlagsEXT
 *
 * Provided by the `XR_EXT_debug_utils` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrDebugUtilsMessageTypeFlagsEXT>
 * @xrentity{XrDebugUtilsMessageTypeFlagBitsEXT}
 * @see DebugUtilsMessageTypeFlagBitsEXT, xr::Flags
 */
using DebugUtilsMessageTypeFlagsEXT =
    Flags<DebugUtilsMessageTypeFlagBitsEXT, XrDebugUtilsMessageTypeFlagsEXT>;

/*!
 * @brief Bitwise OR operator between two DebugUtilsMessageTypeFlagBitsEXT flag bits.
 * @see DebugUtilsMessageTypeFlagBitsEXT, DebugUtilsMessageTypeFlagsEXT, xr::Flags
 */
OPENXR_HPP_INLINE DebugUtilsMessageTypeFlagsEXT operator|(DebugUtilsMessageTypeFlagBitsEXT bit0,
                                                          DebugUtilsMessageTypeFlagBitsEXT bit1) {
  return DebugUtilsMessageTypeFlagsEXT(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a DebugUtilsMessageTypeFlagBitsEXT flag bit.
 * @see DebugUtilsMessageTypeFlagBitsEXT, DebugUtilsMessageTypeFlagsEXT, xr::Flags
 */
OPENXR_HPP_INLINE DebugUtilsMessageTypeFlagsEXT operator~(DebugUtilsMessageTypeFlagBitsEXT bits) {
  return ~(DebugUtilsMessageTypeFlagsEXT(bits));
}

#endif  // XR_EXT_debug_utils

#ifdef XR_EXTX_overlay
/*!
 * @brief Flag bits for XrOverlaySessionCreateFlagsEXTX
 *
 * Provided by the `XR_EXTX_overlay` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrOverlaySessionCreateFlagBitsEXTX>
 * @xrentity{XrOverlaySessionCreateFlagBitsEXTX}
 * @see OverlaySessionCreateFlagsEXTX
 */
enum class OverlaySessionCreateFlagBitsEXTX : XrFlags64 { None = 0, AllBits = 0 };

/*!
 * @brief Flags class projection of XrOverlaySessionCreateFlagsEXTX
 *
 * Provided by the `XR_EXTX_overlay` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrOverlaySessionCreateFlagsEXTX>
 * @xrentity{XrOverlaySessionCreateFlagBitsEXTX}
 * @see OverlaySessionCreateFlagBitsEXTX, xr::Flags
 */
using OverlaySessionCreateFlagsEXTX =
    Flags<OverlaySessionCreateFlagBitsEXTX, XrOverlaySessionCreateFlagsEXTX>;

/*!
 * @brief Bitwise OR operator between two OverlaySessionCreateFlagBitsEXTX flag bits.
 * @see OverlaySessionCreateFlagBitsEXTX, OverlaySessionCreateFlagsEXTX, xr::Flags
 */
OPENXR_HPP_INLINE OverlaySessionCreateFlagsEXTX operator|(OverlaySessionCreateFlagBitsEXTX bit0,
                                                          OverlaySessionCreateFlagBitsEXTX bit1) {
  return OverlaySessionCreateFlagsEXTX(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a OverlaySessionCreateFlagBitsEXTX flag bit.
 * @see OverlaySessionCreateFlagBitsEXTX, OverlaySessionCreateFlagsEXTX, xr::Flags
 */
OPENXR_HPP_INLINE OverlaySessionCreateFlagsEXTX operator~(OverlaySessionCreateFlagBitsEXTX bits) {
  return ~(OverlaySessionCreateFlagsEXTX(bits));
}

#endif  // XR_EXTX_overlay

#ifdef XR_EXTX_overlay
/*!
 * @brief Flag bits for XrOverlayMainSessionFlagsEXTX
 *
 * Provided by the `XR_EXTX_overlay` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrOverlayMainSessionFlagBitsEXTX>
 * @xrentity{XrOverlayMainSessionFlagBitsEXTX}
 * @see OverlayMainSessionFlagsEXTX
 */
enum class OverlayMainSessionFlagBitsEXTX : XrFlags64 {
  None = 0,
  EnabledCompositionLayerInfoDepth =
      XR_OVERLAY_MAIN_SESSION_ENABLED_COMPOSITION_LAYER_INFO_DEPTH_BIT_EXTX,
  AllBits = XR_OVERLAY_MAIN_SESSION_ENABLED_COMPOSITION_LAYER_INFO_DEPTH_BIT_EXTX
};

/*!
 * @brief Flags class projection of XrOverlayMainSessionFlagsEXTX
 *
 * Provided by the `XR_EXTX_overlay` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrOverlayMainSessionFlagsEXTX>
 * @xrentity{XrOverlayMainSessionFlagBitsEXTX}
 * @see OverlayMainSessionFlagBitsEXTX, xr::Flags
 */
using OverlayMainSessionFlagsEXTX =
    Flags<OverlayMainSessionFlagBitsEXTX, XrOverlayMainSessionFlagsEXTX>;

/*!
 * @brief Bitwise OR operator between two OverlayMainSessionFlagBitsEXTX flag bits.
 * @see OverlayMainSessionFlagBitsEXTX, OverlayMainSessionFlagsEXTX, xr::Flags
 */
OPENXR_HPP_INLINE OverlayMainSessionFlagsEXTX operator|(OverlayMainSessionFlagBitsEXTX bit0,
                                                        OverlayMainSessionFlagBitsEXTX bit1) {
  return OverlayMainSessionFlagsEXTX(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a OverlayMainSessionFlagBitsEXTX flag bit.
 * @see OverlayMainSessionFlagBitsEXTX, OverlayMainSessionFlagsEXTX, xr::Flags
 */
OPENXR_HPP_INLINE OverlayMainSessionFlagsEXTX operator~(OverlayMainSessionFlagBitsEXTX bits) {
  return ~(OverlayMainSessionFlagsEXTX(bits));
}

#endif  // XR_EXTX_overlay

#ifdef XR_FB_composition_layer_image_layout
/*!
 * @brief Flag bits for XrCompositionLayerImageLayoutFlagsFB
 *
 * Provided by the `XR_FB_composition_layer_image_layout` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrCompositionLayerImageLayoutFlagBitsFB>
 * @xrentity{XrCompositionLayerImageLayoutFlagBitsFB}
 * @see CompositionLayerImageLayoutFlagsFB
 */
enum class CompositionLayerImageLayoutFlagBitsFB : XrFlags64 {
  None = 0,
  VerticalFlip = XR_COMPOSITION_LAYER_IMAGE_LAYOUT_VERTICAL_FLIP_BIT_FB,
  AllBits = XR_COMPOSITION_LAYER_IMAGE_LAYOUT_VERTICAL_FLIP_BIT_FB
};

/*!
 * @brief Flags class projection of XrCompositionLayerImageLayoutFlagsFB
 *
 * Provided by the `XR_FB_composition_layer_image_layout` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrCompositionLayerImageLayoutFlagsFB>
 * @xrentity{XrCompositionLayerImageLayoutFlagBitsFB}
 * @see CompositionLayerImageLayoutFlagBitsFB, xr::Flags
 */
using CompositionLayerImageLayoutFlagsFB =
    Flags<CompositionLayerImageLayoutFlagBitsFB, XrCompositionLayerImageLayoutFlagsFB>;

/*!
 * @brief Bitwise OR operator between two CompositionLayerImageLayoutFlagBitsFB flag bits.
 * @see CompositionLayerImageLayoutFlagBitsFB, CompositionLayerImageLayoutFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE CompositionLayerImageLayoutFlagsFB
operator|(CompositionLayerImageLayoutFlagBitsFB bit0, CompositionLayerImageLayoutFlagBitsFB bit1) {
  return CompositionLayerImageLayoutFlagsFB(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a CompositionLayerImageLayoutFlagBitsFB flag bit.
 * @see CompositionLayerImageLayoutFlagBitsFB, CompositionLayerImageLayoutFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE CompositionLayerImageLayoutFlagsFB
operator~(CompositionLayerImageLayoutFlagBitsFB bits) {
  return ~(CompositionLayerImageLayoutFlagsFB(bits));
}

#endif  // XR_FB_composition_layer_image_layout

#ifdef XR_FB_android_surface_swapchain_create
#if defined(XR_USE_PLATFORM_ANDROID)
/*!
 * @brief Flag bits for XrAndroidSurfaceSwapchainFlagsFB
 *
 * Provided by the `XR_FB_android_surface_swapchain_create` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrAndroidSurfaceSwapchainFlagBitsFB>
 * @xrentity{XrAndroidSurfaceSwapchainFlagBitsFB}
 * @see AndroidSurfaceSwapchainFlagsFB
 */
enum class AndroidSurfaceSwapchainFlagBitsFB : XrFlags64 {
  None = 0,
  Synchronous = XR_ANDROID_SURFACE_SWAPCHAIN_SYNCHRONOUS_BIT_FB,
  UseTimestamps = XR_ANDROID_SURFACE_SWAPCHAIN_USE_TIMESTAMPS_BIT_FB,
  AllBits = XR_ANDROID_SURFACE_SWAPCHAIN_SYNCHRONOUS_BIT_FB |
            XR_ANDROID_SURFACE_SWAPCHAIN_USE_TIMESTAMPS_BIT_FB
};

/*!
 * @brief Flags class projection of XrAndroidSurfaceSwapchainFlagsFB
 *
 * Provided by the `XR_FB_android_surface_swapchain_create` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrAndroidSurfaceSwapchainFlagsFB>
 * @xrentity{XrAndroidSurfaceSwapchainFlagBitsFB}
 * @see AndroidSurfaceSwapchainFlagBitsFB, xr::Flags
 */
using AndroidSurfaceSwapchainFlagsFB =
    Flags<AndroidSurfaceSwapchainFlagBitsFB, XrAndroidSurfaceSwapchainFlagsFB>;

/*!
 * @brief Bitwise OR operator between two AndroidSurfaceSwapchainFlagBitsFB flag bits.
 * @see AndroidSurfaceSwapchainFlagBitsFB, AndroidSurfaceSwapchainFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE AndroidSurfaceSwapchainFlagsFB operator|(AndroidSurfaceSwapchainFlagBitsFB bit0,
                                                           AndroidSurfaceSwapchainFlagBitsFB bit1) {
  return AndroidSurfaceSwapchainFlagsFB(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a AndroidSurfaceSwapchainFlagBitsFB flag bit.
 * @see AndroidSurfaceSwapchainFlagBitsFB, AndroidSurfaceSwapchainFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE AndroidSurfaceSwapchainFlagsFB operator~(AndroidSurfaceSwapchainFlagBitsFB bits) {
  return ~(AndroidSurfaceSwapchainFlagsFB(bits));
}

#endif  // defined(XR_USE_PLATFORM_ANDROID)
#endif  // XR_FB_android_surface_swapchain_create

#ifdef XR_FB_composition_layer_secure_content
/*!
 * @brief Flag bits for XrCompositionLayerSecureContentFlagsFB
 *
 * Provided by the `XR_FB_composition_layer_secure_content` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrCompositionLayerSecureContentFlagBitsFB>
 * @xrentity{XrCompositionLayerSecureContentFlagBitsFB}
 * @see CompositionLayerSecureContentFlagsFB
 */
enum class CompositionLayerSecureContentFlagBitsFB : XrFlags64 {
  None = 0,
  ExcludeLayer = XR_COMPOSITION_LAYER_SECURE_CONTENT_EXCLUDE_LAYER_BIT_FB,
  ReplaceLayer = XR_COMPOSITION_LAYER_SECURE_CONTENT_REPLACE_LAYER_BIT_FB,
  AllBits = XR_COMPOSITION_LAYER_SECURE_CONTENT_EXCLUDE_LAYER_BIT_FB |
            XR_COMPOSITION_LAYER_SECURE_CONTENT_REPLACE_LAYER_BIT_FB
};

/*!
 * @brief Flags class projection of XrCompositionLayerSecureContentFlagsFB
 *
 * Provided by the `XR_FB_composition_layer_secure_content` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrCompositionLayerSecureContentFlagsFB>
 * @xrentity{XrCompositionLayerSecureContentFlagBitsFB}
 * @see CompositionLayerSecureContentFlagBitsFB, xr::Flags
 */
using CompositionLayerSecureContentFlagsFB =
    Flags<CompositionLayerSecureContentFlagBitsFB, XrCompositionLayerSecureContentFlagsFB>;

/*!
 * @brief Bitwise OR operator between two CompositionLayerSecureContentFlagBitsFB flag bits.
 * @see CompositionLayerSecureContentFlagBitsFB, CompositionLayerSecureContentFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE CompositionLayerSecureContentFlagsFB operator|(
    CompositionLayerSecureContentFlagBitsFB bit0, CompositionLayerSecureContentFlagBitsFB bit1) {
  return CompositionLayerSecureContentFlagsFB(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a CompositionLayerSecureContentFlagBitsFB flag bit.
 * @see CompositionLayerSecureContentFlagBitsFB, CompositionLayerSecureContentFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE CompositionLayerSecureContentFlagsFB
operator~(CompositionLayerSecureContentFlagBitsFB bits) {
  return ~(CompositionLayerSecureContentFlagsFB(bits));
}

#endif  // XR_FB_composition_layer_secure_content

#ifdef XR_FB_hand_tracking_aim
/*!
 * @brief Flag bits for XrHandTrackingAimFlagsFB
 *
 * Provided by the `XR_FB_hand_tracking_aim` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrHandTrackingAimFlagBitsFB>
 * @xrentity{XrHandTrackingAimFlagBitsFB}
 * @see HandTrackingAimFlagsFB
 */
enum class HandTrackingAimFlagBitsFB : XrFlags64 {
  None = 0,
  Computed = XR_HAND_TRACKING_AIM_COMPUTED_BIT_FB,
  Valid = XR_HAND_TRACKING_AIM_VALID_BIT_FB,
  IndexPinching = XR_HAND_TRACKING_AIM_INDEX_PINCHING_BIT_FB,
  MiddlePinching = XR_HAND_TRACKING_AIM_MIDDLE_PINCHING_BIT_FB,
  RingPinching = XR_HAND_TRACKING_AIM_RING_PINCHING_BIT_FB,
  LittlePinching = XR_HAND_TRACKING_AIM_LITTLE_PINCHING_BIT_FB,
  SystemGesture = XR_HAND_TRACKING_AIM_SYSTEM_GESTURE_BIT_FB,
  DominantHand = XR_HAND_TRACKING_AIM_DOMINANT_HAND_BIT_FB,
  MenuPressed = XR_HAND_TRACKING_AIM_MENU_PRESSED_BIT_FB,
  AllBits =
      XR_HAND_TRACKING_AIM_COMPUTED_BIT_FB | XR_HAND_TRACKING_AIM_VALID_BIT_FB |
      XR_HAND_TRACKING_AIM_INDEX_PINCHING_BIT_FB | XR_HAND_TRACKING_AIM_MIDDLE_PINCHING_BIT_FB |
      XR_HAND_TRACKING_AIM_RING_PINCHING_BIT_FB | XR_HAND_TRACKING_AIM_LITTLE_PINCHING_BIT_FB |
      XR_HAND_TRACKING_AIM_SYSTEM_GESTURE_BIT_FB | XR_HAND_TRACKING_AIM_DOMINANT_HAND_BIT_FB |
      XR_HAND_TRACKING_AIM_MENU_PRESSED_BIT_FB
};

/*!
 * @brief Flags class projection of XrHandTrackingAimFlagsFB
 *
 * Provided by the `XR_FB_hand_tracking_aim` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrHandTrackingAimFlagsFB>
 * @xrentity{XrHandTrackingAimFlagBitsFB}
 * @see HandTrackingAimFlagBitsFB, xr::Flags
 */
using HandTrackingAimFlagsFB = Flags<HandTrackingAimFlagBitsFB, XrHandTrackingAimFlagsFB>;

/*!
 * @brief Bitwise OR operator between two HandTrackingAimFlagBitsFB flag bits.
 * @see HandTrackingAimFlagBitsFB, HandTrackingAimFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE HandTrackingAimFlagsFB operator|(HandTrackingAimFlagBitsFB bit0,
                                                   HandTrackingAimFlagBitsFB bit1) {
  return HandTrackingAimFlagsFB(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a HandTrackingAimFlagBitsFB flag bit.
 * @see HandTrackingAimFlagBitsFB, HandTrackingAimFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE HandTrackingAimFlagsFB operator~(HandTrackingAimFlagBitsFB bits) {
  return ~(HandTrackingAimFlagsFB(bits));
}

#endif  // XR_FB_hand_tracking_aim

#ifdef XR_FB_foveation
/*!
 * @brief Flag bits for XrSwapchainCreateFoveationFlagsFB
 *
 * Provided by the `XR_FB_foveation` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrSwapchainCreateFoveationFlagBitsFB>
 * @xrentity{XrSwapchainCreateFoveationFlagBitsFB}
 * @see SwapchainCreateFoveationFlagsFB
 */
enum class SwapchainCreateFoveationFlagBitsFB : XrFlags64 {
  None = 0,
  ScaledBin = XR_SWAPCHAIN_CREATE_FOVEATION_SCALED_BIN_BIT_FB,
  FragmentDensityMap = XR_SWAPCHAIN_CREATE_FOVEATION_FRAGMENT_DENSITY_MAP_BIT_FB,
  AllBits = XR_SWAPCHAIN_CREATE_FOVEATION_SCALED_BIN_BIT_FB |
            XR_SWAPCHAIN_CREATE_FOVEATION_FRAGMENT_DENSITY_MAP_BIT_FB
};

/*!
 * @brief Flags class projection of XrSwapchainCreateFoveationFlagsFB
 *
 * Provided by the `XR_FB_foveation` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrSwapchainCreateFoveationFlagsFB>
 * @xrentity{XrSwapchainCreateFoveationFlagBitsFB}
 * @see SwapchainCreateFoveationFlagBitsFB, xr::Flags
 */
using SwapchainCreateFoveationFlagsFB =
    Flags<SwapchainCreateFoveationFlagBitsFB, XrSwapchainCreateFoveationFlagsFB>;

/*!
 * @brief Bitwise OR operator between two SwapchainCreateFoveationFlagBitsFB flag bits.
 * @see SwapchainCreateFoveationFlagBitsFB, SwapchainCreateFoveationFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE SwapchainCreateFoveationFlagsFB
operator|(SwapchainCreateFoveationFlagBitsFB bit0, SwapchainCreateFoveationFlagBitsFB bit1) {
  return SwapchainCreateFoveationFlagsFB(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a SwapchainCreateFoveationFlagBitsFB flag bit.
 * @see SwapchainCreateFoveationFlagBitsFB, SwapchainCreateFoveationFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE SwapchainCreateFoveationFlagsFB
operator~(SwapchainCreateFoveationFlagBitsFB bits) {
  return ~(SwapchainCreateFoveationFlagsFB(bits));
}

#endif  // XR_FB_foveation

#ifdef XR_FB_foveation
/*!
 * @brief Flag bits for XrSwapchainStateFoveationFlagsFB
 *
 * Provided by the `XR_FB_foveation` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrSwapchainStateFoveationFlagBitsFB>
 * @xrentity{XrSwapchainStateFoveationFlagBitsFB}
 * @see SwapchainStateFoveationFlagsFB
 */
enum class SwapchainStateFoveationFlagBitsFB : XrFlags64 { None = 0, AllBits = 0 };

/*!
 * @brief Flags class projection of XrSwapchainStateFoveationFlagsFB
 *
 * Provided by the `XR_FB_foveation` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrSwapchainStateFoveationFlagsFB>
 * @xrentity{XrSwapchainStateFoveationFlagBitsFB}
 * @see SwapchainStateFoveationFlagBitsFB, xr::Flags
 */
using SwapchainStateFoveationFlagsFB =
    Flags<SwapchainStateFoveationFlagBitsFB, XrSwapchainStateFoveationFlagsFB>;

/*!
 * @brief Bitwise OR operator between two SwapchainStateFoveationFlagBitsFB flag bits.
 * @see SwapchainStateFoveationFlagBitsFB, SwapchainStateFoveationFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE SwapchainStateFoveationFlagsFB operator|(SwapchainStateFoveationFlagBitsFB bit0,
                                                           SwapchainStateFoveationFlagBitsFB bit1) {
  return SwapchainStateFoveationFlagsFB(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a SwapchainStateFoveationFlagBitsFB flag bit.
 * @see SwapchainStateFoveationFlagBitsFB, SwapchainStateFoveationFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE SwapchainStateFoveationFlagsFB operator~(SwapchainStateFoveationFlagBitsFB bits) {
  return ~(SwapchainStateFoveationFlagsFB(bits));
}

#endif  // XR_FB_foveation

#ifdef XR_FB_keyboard_tracking
/*!
 * @brief Flag bits for XrKeyboardTrackingFlagsFB
 *
 * Provided by the `XR_FB_keyboard_tracking` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrKeyboardTrackingFlagBitsFB>
 * @xrentity{XrKeyboardTrackingFlagBitsFB}
 * @see KeyboardTrackingFlagsFB
 */
enum class KeyboardTrackingFlagBitsFB : XrFlags64 {
  None = 0,
  Exists = XR_KEYBOARD_TRACKING_EXISTS_BIT_FB,
  Local = XR_KEYBOARD_TRACKING_LOCAL_BIT_FB,
  Remote = XR_KEYBOARD_TRACKING_REMOTE_BIT_FB,
  Connected = XR_KEYBOARD_TRACKING_CONNECTED_BIT_FB,
  AllBits = XR_KEYBOARD_TRACKING_EXISTS_BIT_FB | XR_KEYBOARD_TRACKING_LOCAL_BIT_FB |
            XR_KEYBOARD_TRACKING_REMOTE_BIT_FB | XR_KEYBOARD_TRACKING_CONNECTED_BIT_FB
};

/*!
 * @brief Flags class projection of XrKeyboardTrackingFlagsFB
 *
 * Provided by the `XR_FB_keyboard_tracking` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrKeyboardTrackingFlagsFB>
 * @xrentity{XrKeyboardTrackingFlagBitsFB}
 * @see KeyboardTrackingFlagBitsFB, xr::Flags
 */
using KeyboardTrackingFlagsFB = Flags<KeyboardTrackingFlagBitsFB, XrKeyboardTrackingFlagsFB>;

/*!
 * @brief Bitwise OR operator between two KeyboardTrackingFlagBitsFB flag bits.
 * @see KeyboardTrackingFlagBitsFB, KeyboardTrackingFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE KeyboardTrackingFlagsFB operator|(KeyboardTrackingFlagBitsFB bit0,
                                                    KeyboardTrackingFlagBitsFB bit1) {
  return KeyboardTrackingFlagsFB(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a KeyboardTrackingFlagBitsFB flag bit.
 * @see KeyboardTrackingFlagBitsFB, KeyboardTrackingFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE KeyboardTrackingFlagsFB operator~(KeyboardTrackingFlagBitsFB bits) {
  return ~(KeyboardTrackingFlagsFB(bits));
}

#endif  // XR_FB_keyboard_tracking

#ifdef XR_FB_keyboard_tracking
/*!
 * @brief Flag bits for XrKeyboardTrackingQueryFlagsFB
 *
 * Provided by the `XR_FB_keyboard_tracking` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrKeyboardTrackingQueryFlagBitsFB>
 * @xrentity{XrKeyboardTrackingQueryFlagBitsFB}
 * @see KeyboardTrackingQueryFlagsFB
 */
enum class KeyboardTrackingQueryFlagBitsFB : XrFlags64 {
  None = 0,
  Local = XR_KEYBOARD_TRACKING_QUERY_LOCAL_BIT_FB,
  Remote = XR_KEYBOARD_TRACKING_QUERY_REMOTE_BIT_FB,
  AllBits = XR_KEYBOARD_TRACKING_QUERY_LOCAL_BIT_FB | XR_KEYBOARD_TRACKING_QUERY_REMOTE_BIT_FB
};

/*!
 * @brief Flags class projection of XrKeyboardTrackingQueryFlagsFB
 *
 * Provided by the `XR_FB_keyboard_tracking` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrKeyboardTrackingQueryFlagsFB>
 * @xrentity{XrKeyboardTrackingQueryFlagBitsFB}
 * @see KeyboardTrackingQueryFlagBitsFB, xr::Flags
 */
using KeyboardTrackingQueryFlagsFB =
    Flags<KeyboardTrackingQueryFlagBitsFB, XrKeyboardTrackingQueryFlagsFB>;

/*!
 * @brief Bitwise OR operator between two KeyboardTrackingQueryFlagBitsFB flag bits.
 * @see KeyboardTrackingQueryFlagBitsFB, KeyboardTrackingQueryFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE KeyboardTrackingQueryFlagsFB operator|(KeyboardTrackingQueryFlagBitsFB bit0,
                                                         KeyboardTrackingQueryFlagBitsFB bit1) {
  return KeyboardTrackingQueryFlagsFB(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a KeyboardTrackingQueryFlagBitsFB flag bit.
 * @see KeyboardTrackingQueryFlagBitsFB, KeyboardTrackingQueryFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE KeyboardTrackingQueryFlagsFB operator~(KeyboardTrackingQueryFlagBitsFB bits) {
  return ~(KeyboardTrackingQueryFlagsFB(bits));
}

#endif  // XR_FB_keyboard_tracking

#ifdef XR_FB_triangle_mesh
/*!
 * @brief Flag bits for XrTriangleMeshFlagsFB
 *
 * Provided by the `XR_FB_triangle_mesh` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrTriangleMeshFlagBitsFB>
 * @xrentity{XrTriangleMeshFlagBitsFB}
 * @see TriangleMeshFlagsFB
 */
enum class TriangleMeshFlagBitsFB : XrFlags64 {
  None = 0,
  Mutable = XR_TRIANGLE_MESH_MUTABLE_BIT_FB,
  AllBits = XR_TRIANGLE_MESH_MUTABLE_BIT_FB
};

/*!
 * @brief Flags class projection of XrTriangleMeshFlagsFB
 *
 * Provided by the `XR_FB_triangle_mesh` extension.
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrTriangleMeshFlagsFB>
 * @xrentity{XrTriangleMeshFlagBitsFB}
 * @see TriangleMeshFlagBitsFB, xr::Flags
 */
using TriangleMeshFlagsFB = Flags<TriangleMeshFlagBitsFB, XrTriangleMeshFlagsFB>;

/*!
 * @brief Bitwise OR operator between two TriangleMeshFlagBitsFB flag bits.
 * @see TriangleMeshFlagBitsFB, TriangleMeshFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE TriangleMeshFlagsFB operator|(TriangleMeshFlagBitsFB bit0,
                                                TriangleMeshFlagBitsFB bit1) {
  return TriangleMeshFlagsFB(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a TriangleMeshFlagBitsFB flag bit.
 * @see TriangleMeshFlagBitsFB, TriangleMeshFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE TriangleMeshFlagsFB operator~(TriangleMeshFlagBitsFB bits) {
  return ~(TriangleMeshFlagsFB(bits));
}

#endif  // XR_FB_triangle_mesh

#ifdef XR_FB_passthrough
/*!
 * @brief Flag bits for XrPassthroughFlagsFB
 *
 * Provided by the `XR_FB_passthrough` extension.
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrPassthroughFlagBitsFB>
 * @xrentity{XrPassthroughFlagBitsFB}
 * @see PassthroughFlagsFB
 */
enum class PassthroughFlagBitsFB : XrFlags64 {
  None = 0,
  IsRunningAtCreation = XR_PASSTHROUGH_IS_RUNNING_AT_CREATION_BIT_FB,
  AllBits = XR_PASSTHROUGH_IS_RUNNING_AT_CREATION_BIT_FB
};

/*!
 * @brief Flags class projection of XrPassthroughFlagsFB
 *
 * Provided by the `XR_FB_passthrough` extension.
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrPassthroughFlagsFB>
 * @xrentity{XrPassthroughFlagBitsFB}
 * @see PassthroughFlagBitsFB, xr::Flags
 */
using PassthroughFlagsFB = Flags<PassthroughFlagBitsFB, XrPassthroughFlagsFB>;

/*!
 * @brief Bitwise OR operator between two PassthroughFlagBitsFB flag bits.
 * @see PassthroughFlagBitsFB, PassthroughFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE PassthroughFlagsFB operator|(PassthroughFlagBitsFB bit0,
                                               PassthroughFlagBitsFB bit1) {
  return PassthroughFlagsFB(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a PassthroughFlagBitsFB flag bit.
 * @see PassthroughFlagBitsFB, PassthroughFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE PassthroughFlagsFB operator~(PassthroughFlagBitsFB bits) {
  return ~(PassthroughFlagsFB(bits));
}

#endif  // XR_FB_passthrough

#ifdef XR_FB_passthrough
/*!
 * @brief Flag bits for XrPassthroughStateChangedFlagsFB
 *
 * Provided by the `XR_FB_passthrough` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrPassthroughStateChangedFlagBitsFB>
 * @xrentity{XrPassthroughStateChangedFlagBitsFB}
 * @see PassthroughStateChangedFlagsFB
 */
enum class PassthroughStateChangedFlagBitsFB : XrFlags64 {
  None = 0,
  ReinitRequired = XR_PASSTHROUGH_STATE_CHANGED_REINIT_REQUIRED_BIT_FB,
  NonRecoverableError = XR_PASSTHROUGH_STATE_CHANGED_NON_RECOVERABLE_ERROR_BIT_FB,
  RecoverableError = XR_PASSTHROUGH_STATE_CHANGED_RECOVERABLE_ERROR_BIT_FB,
  RestoredError = XR_PASSTHROUGH_STATE_CHANGED_RESTORED_ERROR_BIT_FB,
  AllBits = XR_PASSTHROUGH_STATE_CHANGED_REINIT_REQUIRED_BIT_FB |
            XR_PASSTHROUGH_STATE_CHANGED_NON_RECOVERABLE_ERROR_BIT_FB |
            XR_PASSTHROUGH_STATE_CHANGED_RECOVERABLE_ERROR_BIT_FB |
            XR_PASSTHROUGH_STATE_CHANGED_RESTORED_ERROR_BIT_FB
};

/*!
 * @brief Flags class projection of XrPassthroughStateChangedFlagsFB
 *
 * Provided by the `XR_FB_passthrough` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrPassthroughStateChangedFlagsFB>
 * @xrentity{XrPassthroughStateChangedFlagBitsFB}
 * @see PassthroughStateChangedFlagBitsFB, xr::Flags
 */
using PassthroughStateChangedFlagsFB =
    Flags<PassthroughStateChangedFlagBitsFB, XrPassthroughStateChangedFlagsFB>;

/*!
 * @brief Bitwise OR operator between two PassthroughStateChangedFlagBitsFB flag bits.
 * @see PassthroughStateChangedFlagBitsFB, PassthroughStateChangedFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE PassthroughStateChangedFlagsFB operator|(PassthroughStateChangedFlagBitsFB bit0,
                                                           PassthroughStateChangedFlagBitsFB bit1) {
  return PassthroughStateChangedFlagsFB(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a PassthroughStateChangedFlagBitsFB flag bit.
 * @see PassthroughStateChangedFlagBitsFB, PassthroughStateChangedFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE PassthroughStateChangedFlagsFB operator~(PassthroughStateChangedFlagBitsFB bits) {
  return ~(PassthroughStateChangedFlagsFB(bits));
}

#endif  // XR_FB_passthrough

#ifdef XR_FB_render_model
/*!
 * @brief Flag bits for XrRenderModelFlagsFB
 *
 * Provided by the `XR_FB_render_model` extension.
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrRenderModelFlagBitsFB>
 * @xrentity{XrRenderModelFlagBitsFB}
 * @see RenderModelFlagsFB
 */
enum class RenderModelFlagBitsFB : XrFlags64 { None = 0, AllBits = 0 };

/*!
 * @brief Flags class projection of XrRenderModelFlagsFB
 *
 * Provided by the `XR_FB_render_model` extension.
 *
 * @see <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrRenderModelFlagsFB>
 * @xrentity{XrRenderModelFlagBitsFB}
 * @see RenderModelFlagBitsFB, xr::Flags
 */
using RenderModelFlagsFB = Flags<RenderModelFlagBitsFB, XrRenderModelFlagsFB>;

/*!
 * @brief Bitwise OR operator between two RenderModelFlagBitsFB flag bits.
 * @see RenderModelFlagBitsFB, RenderModelFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE RenderModelFlagsFB operator|(RenderModelFlagBitsFB bit0,
                                               RenderModelFlagBitsFB bit1) {
  return RenderModelFlagsFB(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a RenderModelFlagBitsFB flag bit.
 * @see RenderModelFlagBitsFB, RenderModelFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE RenderModelFlagsFB operator~(RenderModelFlagBitsFB bits) {
  return ~(RenderModelFlagsFB(bits));
}

#endif  // XR_FB_render_model

#ifdef XR_FB_space_warp
/*!
 * @brief Flag bits for XrCompositionLayerSpaceWarpInfoFlagsFB
 *
 * Provided by the `XR_FB_space_warp` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrCompositionLayerSpaceWarpInfoFlagBitsFB>
 * @xrentity{XrCompositionLayerSpaceWarpInfoFlagBitsFB}
 * @see CompositionLayerSpaceWarpInfoFlagsFB
 */
enum class CompositionLayerSpaceWarpInfoFlagBitsFB : XrFlags64 { None = 0, AllBits = 0 };

/*!
 * @brief Flags class projection of XrCompositionLayerSpaceWarpInfoFlagsFB
 *
 * Provided by the `XR_FB_space_warp` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrCompositionLayerSpaceWarpInfoFlagsFB>
 * @xrentity{XrCompositionLayerSpaceWarpInfoFlagBitsFB}
 * @see CompositionLayerSpaceWarpInfoFlagBitsFB, xr::Flags
 */
using CompositionLayerSpaceWarpInfoFlagsFB =
    Flags<CompositionLayerSpaceWarpInfoFlagBitsFB, XrCompositionLayerSpaceWarpInfoFlagsFB>;

/*!
 * @brief Bitwise OR operator between two CompositionLayerSpaceWarpInfoFlagBitsFB flag bits.
 * @see CompositionLayerSpaceWarpInfoFlagBitsFB, CompositionLayerSpaceWarpInfoFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE CompositionLayerSpaceWarpInfoFlagsFB operator|(
    CompositionLayerSpaceWarpInfoFlagBitsFB bit0, CompositionLayerSpaceWarpInfoFlagBitsFB bit1) {
  return CompositionLayerSpaceWarpInfoFlagsFB(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a CompositionLayerSpaceWarpInfoFlagBitsFB flag bit.
 * @see CompositionLayerSpaceWarpInfoFlagBitsFB, CompositionLayerSpaceWarpInfoFlagsFB, xr::Flags
 */
OPENXR_HPP_INLINE CompositionLayerSpaceWarpInfoFlagsFB
operator~(CompositionLayerSpaceWarpInfoFlagBitsFB bits) {
  return ~(CompositionLayerSpaceWarpInfoFlagsFB(bits));
}

#endif  // XR_FB_space_warp

#ifdef XR_ALMALENCE_digital_lens_control
/*!
 * @brief Flag bits for XrDigitalLensControlFlagsALMALENCE
 *
 * Provided by the `XR_ALMALENCE_digital_lens_control` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrDigitalLensControlFlagBitsALMALENCE>
 * @xrentity{XrDigitalLensControlFlagBitsALMALENCE}
 * @see DigitalLensControlFlagsALMALENCE
 */
enum class DigitalLensControlFlagBitsALMALENCE : XrFlags64 {
  None = 0,
  ProcessingDisable = XR_DIGITAL_LENS_CONTROL_PROCESSING_DISABLE_BIT_ALMALENCE,
  AllBits = XR_DIGITAL_LENS_CONTROL_PROCESSING_DISABLE_BIT_ALMALENCE
};

/*!
 * @brief Flags class projection of XrDigitalLensControlFlagsALMALENCE
 *
 * Provided by the `XR_ALMALENCE_digital_lens_control` extension.
 *
 * @see
 * <https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrDigitalLensControlFlagsALMALENCE>
 * @xrentity{XrDigitalLensControlFlagBitsALMALENCE}
 * @see DigitalLensControlFlagBitsALMALENCE, xr::Flags
 */
using DigitalLensControlFlagsALMALENCE =
    Flags<DigitalLensControlFlagBitsALMALENCE, XrDigitalLensControlFlagsALMALENCE>;

/*!
 * @brief Bitwise OR operator between two DigitalLensControlFlagBitsALMALENCE flag bits.
 * @see DigitalLensControlFlagBitsALMALENCE, DigitalLensControlFlagsALMALENCE, xr::Flags
 */
OPENXR_HPP_INLINE DigitalLensControlFlagsALMALENCE
operator|(DigitalLensControlFlagBitsALMALENCE bit0, DigitalLensControlFlagBitsALMALENCE bit1) {
  return DigitalLensControlFlagsALMALENCE(bit0) | bit1;
}

/*!
 * @brief Bitwise negation operator of a DigitalLensControlFlagBitsALMALENCE flag bit.
 * @see DigitalLensControlFlagBitsALMALENCE, DigitalLensControlFlagsALMALENCE, xr::Flags
 */
OPENXR_HPP_INLINE DigitalLensControlFlagsALMALENCE
operator~(DigitalLensControlFlagBitsALMALENCE bits) {
  return ~(DigitalLensControlFlagsALMALENCE(bits));
}

#endif  // XR_ALMALENCE_digital_lens_control
//! @}

}  // namespace OPENXR_HPP_NAMESPACE

#endif  // ifndef OPENXR_FLAGS_HPP_
