// *********** THIS FILE IS GENERATED - DO NOT EDIT ***********
//     See cpp_generator.py for modifications
// ************************************************************

/*
** Copyright (c) 2017-2021 The Khronos Group Inc.
** Copyright (c) 2019-2021 Collabora, Ltd.
**
** Licensed under the Apache License, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
**
**     http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
**
** ---- Exceptions to the Apache 2.0 License: ----
**
** As an exception, if you use this Software to generate code and portions of
** this Software are embedded into the generated code as a result, you may
** redistribute such product without providing attribution as would otherwise
** be required by Sections 4(a), 4(b) and 4(d) of the License.
**
** In addition, if you combine or link code generated by this Software with
** software that is licensed under the GPLv2 or the LGPL v2.0 or 2.1
** ("`Combined Software`") and if a court of competent jurisdiction determines
** that the patent provision (Section 3), the indemnity provision (Section 9)
** or other Section of the License conflicts with the conditions of the
** applicable GPL or LGPL license, you may retroactively and prospectively
** choose to deem waived or otherwise exclude such Section(s) of the License,
** but only in their entirety and only with respect to the Combined Software.
**
*/

/*
** This header is generated from the Khronos OpenXR XML API Registry.
**
*/
#ifndef OPENXR_STRUCTS_FORWARD_HPP_
#define OPENXR_STRUCTS_FORWARD_HPP_
/**
 * @file
 * @brief Forward declarations of all C++ projections of OpenXR structure types.
 * @ingroup structs
 */

#if !defined(OPENXR_HPP_NAMESPACE)
#define OPENXR_HPP_NAMESPACE xr
#endif  // !OPENXR_HPP_NAMESPACE
namespace OPENXR_HPP_NAMESPACE {

struct ApiLayerProperties;
struct ExtensionProperties;
struct ApplicationInfo;
struct InstanceCreateInfo;
struct InstanceProperties;
struct EventDataBuffer;
struct SystemGetInfo;
struct SystemGraphicsProperties;
struct SystemTrackingProperties;
struct SystemProperties;
struct SessionCreateInfo;
struct Vector3f;
struct SpaceVelocity;
struct Quaternionf;
struct Posef;
struct ReferenceSpaceCreateInfo;
struct Extent2Df;
struct ActionSpaceCreateInfo;
struct SpaceLocation;
struct ViewConfigurationProperties;
struct ViewConfigurationView;
struct SwapchainCreateInfo;
struct SwapchainImageBaseHeader;
struct SwapchainImageAcquireInfo;
struct SwapchainImageWaitInfo;
struct SwapchainImageReleaseInfo;
struct SessionBeginInfo;
struct FrameWaitInfo;
struct FrameState;
struct FrameBeginInfo;
struct CompositionLayerBaseHeader;
struct FrameEndInfo;
struct ViewLocateInfo;
struct ViewState;
struct Fovf;
struct View;
struct ActionSetCreateInfo;
struct ActionCreateInfo;
struct ActionSuggestedBinding;
struct InteractionProfileSuggestedBinding;
struct SessionActionSetsAttachInfo;
struct InteractionProfileState;
struct ActionStateGetInfo;
struct ActionStateBoolean;
struct ActionStateFloat;
struct Vector2f;
struct ActionStateVector2f;
struct ActionStatePose;
struct ActiveActionSet;
struct ActionsSyncInfo;
struct BoundSourcesForActionEnumerateInfo;
struct InputSourceLocalizedNameGetInfo;
struct HapticActionInfo;
struct HapticBaseHeader;
struct BaseInStructure;
struct BaseOutStructure;
struct Offset2Di;
struct Extent2Di;
struct Rect2Di;
struct SwapchainSubImage;
struct CompositionLayerProjectionView;
struct CompositionLayerProjection;
struct CompositionLayerQuad;
struct EventDataBaseHeader;
struct EventDataEventsLost;
struct EventDataInstanceLossPending;
struct EventDataSessionStateChanged;
struct EventDataReferenceSpaceChangePending;
struct EventDataInteractionProfileChanged;
struct HapticVibration;
struct Offset2Df;
struct Rect2Df;
struct Vector4f;
struct Color4f;
struct CompositionLayerCubeKHR;
struct InstanceCreateInfoAndroidKHR;
struct CompositionLayerDepthInfoKHR;
struct VulkanSwapchainFormatListCreateInfoKHR;
struct CompositionLayerCylinderKHR;
struct CompositionLayerEquirectKHR;
struct GraphicsBindingOpenGLWin32KHR;
struct GraphicsBindingOpenGLXlibKHR;
struct GraphicsBindingOpenGLXcbKHR;
struct GraphicsBindingOpenGLWaylandKHR;
struct SwapchainImageOpenGLKHR;
struct GraphicsRequirementsOpenGLKHR;
struct GraphicsBindingOpenGLESAndroidKHR;
struct SwapchainImageOpenGLESKHR;
struct GraphicsRequirementsOpenGLESKHR;
struct GraphicsBindingVulkanKHR;
struct SwapchainImageVulkanKHR;
struct GraphicsRequirementsVulkanKHR;
struct GraphicsBindingD3D11KHR;
struct SwapchainImageD3D11KHR;
struct GraphicsRequirementsD3D11KHR;
struct GraphicsBindingD3D12KHR;
struct SwapchainImageD3D12KHR;
struct GraphicsRequirementsD3D12KHR;
struct VisibilityMaskKHR;
struct EventDataVisibilityMaskChangedKHR;
struct CompositionLayerColorScaleBiasKHR;
struct LoaderInitInfoBaseHeaderKHR;
struct LoaderInitInfoAndroidKHR;
struct VulkanInstanceCreateInfoKHR;
struct VulkanDeviceCreateInfoKHR;
struct VulkanGraphicsDeviceGetInfoKHR;
struct CompositionLayerEquirect2KHR;
struct BindingModificationBaseHeaderKHR;
struct BindingModificationsKHR;
struct EventDataPerfSettingsEXT;
struct DebugUtilsObjectNameInfoEXT;
struct DebugUtilsLabelEXT;
struct DebugUtilsMessengerCallbackDataEXT;
struct DebugUtilsMessengerCreateInfoEXT;
struct SystemEyeGazeInteractionPropertiesEXT;
struct EyeGazeSampleTimeEXT;
struct SessionCreateInfoOverlayEXTX;
struct EventDataMainSessionVisibilityChangedEXTX;
struct SpatialAnchorCreateInfoMSFT;
struct SpatialAnchorSpaceCreateInfoMSFT;
struct CompositionLayerImageLayoutFB;
struct CompositionLayerAlphaBlendFB;
struct ViewConfigurationDepthRangeEXT;
struct GraphicsBindingEGLMNDX;
struct SystemHandTrackingPropertiesEXT;
struct HandTrackerCreateInfoEXT;
struct HandJointsLocateInfoEXT;
struct HandJointLocationEXT;
struct HandJointVelocityEXT;
struct HandJointLocationsEXT;
struct HandJointVelocitiesEXT;
struct SystemHandTrackingMeshPropertiesMSFT;
struct HandMeshSpaceCreateInfoMSFT;
struct HandMeshUpdateInfoMSFT;
struct HandMeshIndexBufferMSFT;
struct HandMeshVertexMSFT;
struct HandMeshVertexBufferMSFT;
struct HandMeshMSFT;
struct HandPoseTypeInfoMSFT;
struct SecondaryViewConfigurationSessionBeginInfoMSFT;
struct SecondaryViewConfigurationStateMSFT;
struct SecondaryViewConfigurationFrameStateMSFT;
struct SecondaryViewConfigurationLayerInfoMSFT;
struct SecondaryViewConfigurationFrameEndInfoMSFT;
struct SecondaryViewConfigurationSwapchainCreateInfoMSFT;
struct ViewConfigurationViewFovEPIC;
struct HolographicWindowAttachmentMSFT;
struct CompositionLayerReprojectionInfoMSFT;
struct CompositionLayerReprojectionPlaneOverrideMSFT;
struct AndroidSurfaceSwapchainCreateInfoFB;
struct SwapchainStateBaseHeaderFB;
struct CompositionLayerSecureContentFB;
struct InteractionProfileAnalogThresholdVALVE;
struct HandJointsMotionRangeInfoEXT;
struct UuidMSFT;
struct SceneObserverCreateInfoMSFT;
struct SceneCreateInfoMSFT;
struct SceneSphereBoundMSFT;
struct SceneOrientedBoxBoundMSFT;
struct SceneFrustumBoundMSFT;
struct SceneBoundsMSFT;
struct NewSceneComputeInfoMSFT;
struct VisualMeshComputeLodInfoMSFT;
struct SceneComponentMSFT;
struct SceneComponentsMSFT;
struct SceneComponentsGetInfoMSFT;
struct SceneComponentLocationMSFT;
struct SceneComponentLocationsMSFT;
struct SceneComponentsLocateInfoMSFT;
struct SceneObjectMSFT;
struct SceneObjectsMSFT;
struct SceneComponentParentFilterInfoMSFT;
struct SceneObjectTypesFilterInfoMSFT;
struct ScenePlaneMSFT;
struct ScenePlanesMSFT;
struct ScenePlaneAlignmentFilterInfoMSFT;
struct SceneMeshMSFT;
struct SceneMeshesMSFT;
struct SceneMeshBuffersGetInfoMSFT;
struct SceneMeshBuffersMSFT;
struct SceneMeshVertexBufferMSFT;
struct SceneMeshIndicesUint32MSFT;
struct SceneMeshIndicesUint16MSFT;
struct SerializedSceneFragmentDataGetInfoMSFT;
struct DeserializeSceneFragmentMSFT;
struct SceneDeserializeInfoMSFT;
struct EventDataDisplayRefreshRateChangedFB;
struct ViveTrackerPathsHTCX;
struct EventDataViveTrackerConnectedHTCX;
struct SystemFacialTrackingPropertiesHTC;
struct FacialExpressionsHTC;
struct FacialTrackerCreateInfoHTC;
struct SystemColorSpacePropertiesFB;
struct Vector4sFB;
struct HandTrackingMeshFB;
struct HandTrackingScaleFB;
struct HandTrackingAimStateFB;
struct HandCapsuleFB;
struct HandTrackingCapsulesStateFB;
struct FoveationProfileCreateInfoFB;
struct SwapchainCreateInfoFoveationFB;
struct SwapchainStateFoveationFB;
struct FoveationLevelProfileCreateInfoFB;
struct SystemKeyboardTrackingPropertiesFB;
struct KeyboardTrackingDescriptionFB;
struct KeyboardSpaceCreateInfoFB;
struct KeyboardTrackingQueryFB;
struct TriangleMeshCreateInfoFB;
struct SystemPassthroughPropertiesFB;
struct PassthroughCreateInfoFB;
struct PassthroughLayerCreateInfoFB;
struct CompositionLayerPassthroughFB;
struct GeometryInstanceCreateInfoFB;
struct GeometryInstanceTransformFB;
struct PassthroughStyleFB;
struct PassthroughColorMapMonoToRgbaFB;
struct PassthroughColorMapMonoToMonoFB;
struct EventDataPassthroughStateChangedFB;
struct RenderModelPathInfoFB;
struct RenderModelPropertiesFB;
struct RenderModelBufferFB;
struct RenderModelLoadInfoFB;
struct SystemRenderModelPropertiesFB;
struct ViewLocateFoveatedRenderingVARJO;
struct FoveatedViewConfigurationViewVARJO;
struct SystemFoveatedRenderingPropertiesVARJO;
struct CompositionLayerDepthTestVARJO;
struct SystemMarkerTrackingPropertiesVARJO;
struct EventDataMarkerTrackingUpdateVARJO;
struct MarkerSpaceCreateInfoVARJO;
struct SpatialAnchorPersistenceNameMSFT;
struct SpatialAnchorPersistenceInfoMSFT;
struct SpatialAnchorFromPersistedAnchorCreateInfoMSFT;
struct SwapchainImageFoveationVulkanFB;
struct SwapchainStateAndroidSurfaceDimensionsFB;
struct SwapchainStateSamplerOpenGLESFB;
struct SwapchainStateSamplerVulkanFB;
struct CompositionLayerSpaceWarpInfoFB;
struct SystemSpaceWarpPropertiesFB;
struct DigitalLensControlALMALENCE;
struct PassthroughKeyboardHandsIntensityFB;
struct UuidEXT;
}  // namespace OPENXR_HPP_NAMESPACE

#endif  // ifndef OPENXR_STRUCTS_FORWARD_HPP_
